### ISSUE TITLE
Trouble running tests

### ISSUE THREAD

**Issue by dustinfarris** [JarrodCTaylor/fauxjax#10]
Folowing the instructions in the readme, I was not able to run the tests:

```
$ fauxjax grunt test
Running "coffee:compile" (coffee) task
>> 1 files created.

Running "uglify:my_target" (uglify) task
>> 1 file created.

Running "testem" task
FFatal error: Cannot call method 'split' of undefined
```

**Comment by JarrodCTaylor** [comment]
Well that is interesting. I just `rm -rf`'ed the fauxjax directory and did a new clone and fresh npm install and the tests still ran fine for me. Also travis is just doing a `npm install` followed by a `npm test` and everything runs as expected.

**Comment by dustinfarris** [comment]
`npm test` works!

The README says to run `grunt test` which does not work until after `npm test` has been run at least once.

**Comment by dustinfarris** [comment]
I take that back..  I just deleted and recloned the project, and `grunt test` worked this time around.  I'm not sure what happened before.
