### ISSUE TITLE
How to get the number of requests?

### ISSUE THREAD

**Issue by toranb** [JarrodCTaylor/fauxjax#15]
Jarrod

Love the library -curious if a public api exists to get the # of ajax calls stub'd ? We are trying to verify we only get 1 ajax call instead of 2 but because the intercept func just keeps stubbing it (expected behavior) we can't find a way to get the fakedAjaxCalls length.

Anything like that exist or should we do a PR for this?

**Comment by toranb** [comment]
I think the PR would/could be dead simple :)

```js
    $.fauxjax.fakedAjaxCalls = function() {
        return fakedAjaxCalls;
    };
```

**Comment by JarrodCTaylor** [comment]
Commit 611eaec2124fc94c87626ccb64f24bfd40292a5e added the `fakedAjaxCalls` function. The tests and wiki have been updated to document the new function. 

Let me know if this doesn't satisfy what you were going for.

**Comment by toranb** [comment]
dude you rawk :)

**Comment by toranb** [comment]
Does this need a version bump /tag also?

**Comment by JarrodCTaylor** [comment]
It's got one V 1.0.5 https://github.com/JarrodCTaylor/fauxjax/releases/tag/1.0.5

**Comment by toranb** [comment]
Wow dude -what OSS charity should I donate to for such speedy work :D
