### ISSUE TITLE
[Question]: How to stub xhr for html content?

### ISSUE THREAD

**Issue by toranb** [JarrodCTaylor/fauxjax#17]
@JarrodCTaylor love love love this library :)

Question about mocking an xhr where the data type is html. I have something like the below and I can't seem to find the word "dataType" in the source. Is something like this supported today? If yes, what would I change in the below to tell fauxjax I'm trying to stub an html request? If no, what can I do to help add this/get this feature into fauxjax?

Thank you in advance

```js
        $.ajax({
            url: "https://www.google.com",
            dataType: "html"
        }).then(function(response) {
            //do something w/ the html response
        });
```

**Comment by JarrodCTaylor** [comment]
I don't know if I totally understand what feature you are wanting.

Currently if the value of content in the response of your fauxjax instance has some type of an object then it will be interpreted as json and returned as such. All other strings are just returned as strings as I think that is what jQuery does. So the feature of not having to manage `dataType` or `contentType` was introduced in the 2.0 series (I don't think it was being handled properly in 1.X) 

![screen shot 2015-05-28 at 4 02 49 pm](https://cloud.githubusercontent.com/assets/4416952/7871172/cf91678e-0553-11e5-81cb-b1f35480e61d.png)

The screen shot if from the jQuery docs and if I interpret that correctly then html is just a string which is what happens now. 

Let me know if I am just not following your point.

**Comment by toranb** [comment]
Totally cool -so what is the correct way to stub that $.ajax method I showed above with fauxjax?

**Comment by JarrodCTaylor** [comment]
Something like this? (Sorry for the CoffeeScript the tests are still not babel-ifyed) 

``` javascript
test "Content can be html string and will still be succeffully mocked", (assert) ->
  done = assert.async()
  $.fauxjax.new
    request:
      method: "GET"
      url: "/faux-request"
    response:
      content: "<h1>Everyone loves html</h1>"

  $.ajax
    method: "GET"
    url: "/faux-request"
    data: undefined
    dataType: "html"
    success: (data, textStatus, xhr) ->
      assert.ok(true, "Request did not succeed and should have been successfully faked")
      assert.equal("<h1>Everyone loves html</h1>", data)
    error: (xhr, textStatus) ->
      asert.ok(false, "Error was returned from a request that should have successfully been faked")
    complete: (xhr, textStatus) ->
      done()
```

**Comment by toranb** [comment]
Perfecto ! Thanks for the help @JarrodCTaylor
