### ISSUE TITLE
[QUESTION]: Does this library or will this library get a LICENSE

### ISSUE THREAD

**Issue by williamsbdev** [JarrodCTaylor/fauxjax#18]
We are working on documenting the versions and licenses of all our dependencies. This project does not have a LICENSE and I fear we may not be able to continue using this project without a license. Might I recommend an MIT license?

**Comment by williamsbdev** [comment]
We are using the bower-license node module which looks in the `bower.json` for a `license` key. So this is most important change for me during this request. Please reference [this](https://github.com/ember-cli/ember-resolver/blob/master/bower.json#L4) file.

Thanks!

**Comment by JarrodCTaylor** [comment]
I will look into this one tomorrow

**Comment by JarrodCTaylor** [comment]
Close with commit 53bcafcd663f2359f33fdd4d693108ccb7556a54

**Comment by williamsbdev** [comment]
This is perfect! Thank you for being so quick to get the license added.
