### ISSUE TITLE
Empty body on get does not work in version 1.1.0 if content type is application/json

### ISSUE THREAD

**Issue by benkiefer** [JarrodCTaylor/fauxjax#20]
Will submit a PR shortly

**Comment by JarrodCTaylor** [comment]
PR merged. Closing this issue.

**Comment by JarrodCTaylor** [comment]
@benkiefer  I must admit that I merged this without giving it a close review this morning. Now that I am taking a closer look at this and the other PR from today I have a few questions. What is the use case for ever setting `contentType` on a `GET` seeing as how it is used to specify content being sent to the server?  That seems like a user configuration error more than a bug in fauxjax.

**Comment by williamsbdev** [comment]
@JarrodCTaylor @benkiefer I think that is a fair assessment. We are using @toranb's [ember-promise](https://github.com/toranb/ember-promise) addon and it defaults every request to have `contentType` of `application/json`. This seems less than desirable as we would not be transmitting `POST` data on a `GET` request. Perhaps we can only set the `contentType` if the request is not a `GET` like in my [PR](https://github.com/toranb/ember-promise/pull/5).

**Comment by JarrodCTaylor** [comment]
I will roll back the PR that was related to this issue and see if I can come up with a satisfactory solution for contentTypes other than the default.
