### ISSUE TITLE
Make fauxjax 1.1.0 backwards compatible for content type json requests

### ISSUE THREAD

**Issue by benkiefer** [JarrodCTaylor/fauxjax#22]

**Comment by JarrodCTaylor** [comment]
Are you working on an example/fix for the incompatibilities?

**Comment by benkiefer** [comment]
Yes, working on a PR right now

**Comment by JarrodCTaylor** [comment]
Great

**Comment by JarrodCTaylor** [comment]
After the next release this weekend, please test and open issues with valid test cases if you find anything not working as expected.
