### ISSUE TITLE
Version 1.2.1

### ISSUE THREAD

**Issue by JarrodCTaylor** [JarrodCTaylor/fauxjax#24]
@williamsbdev @benkiefer I just pushed version 1.2.1 which allows you to specify `contentType` on new faux instances. The docs have also been updated to reflect the new defaults. It is my intention that this should properly deal with posting `JSON.stringify` data. Currently the only content types that I would like to make sure are supported are the default `application/x-www-form-urlencoded` and `application/json`. 

It is not the goal of this library or the intended allocation of my free time to make provisions for everything that is technically not prohibited by the HTTP specification. As such it is understood that there could possibly be ways to configure requests that might not get mocked. However, I want this library to be useful to others and if there are any common valid use cases that I have missed or do not behave as expected / desired please open issues/PRs. 

Once you get a chance to run your tests through the latest version and review the results. Let me know if it looks good and we can close this issue or address any concerns.

**Comment by benkiefer** [comment]
Started looking at this tonight. Is the intent to be backwards compatible on this version, or for this to be a breaking change? If you'd like it to be backwards compatible, I can put together a PR.

**Comment by JarrodCTaylor** [comment]
What incompatibilities are you observing?
