### ISSUE TITLE
distribution file for 1.6 did not change

### ISSUE THREAD

**Issue by khornberg** [JarrodCTaylor/fauxjax#32]
Ran `bower install fauxjax -U` and only the `package.json` was updated. It seems that the dist file was not updated. Is that something you want to do or should I run `grunt build` or whatever?

**Comment by JarrodCTaylor** [comment]
Corrected now

**Comment by khornberg** [comment]
Thank you

**Comment by JarrodCTaylor** [comment]
No problem, good catch.
