### ISSUE TITLE
Publish 1.6 to bower

### ISSUE THREAD

**Issue by khornberg** [JarrodCTaylor/fauxjax#33]
Could you publish a new version to bower? The current 1.6 version is not being served.

Going to https://github.com/JarrodCTaylor/fauxjax/tree/1.6.0 makes it seem that the tag needs to be repushed

└──➤ bower install fauxjax
bower cached        https://github.com/JarrodCTaylor/fauxjax.git#1.6.0
bower validate      1.6.0 against https://github.com/JarrodCTaylor/fauxjax.git#*
bower install       fauxjax#1.6.0

fauxjax#1.6.0 bower_components/fauxjax
└──➤ openssl sha1 bower_components/fauxjax/dist/fauxjax.min.js
SHA1(bower_components/fauxjax/dist/fauxjax.min.js)= `770726bd48046b6d64730bd17411422d38f2e215`
└──➤ git clone https://github.com/JarrodCTaylor/fauxjax.git
Cloning into 'fauxjax'...
remote: Counting objects: 563, done.
remote: Total 563 (delta 0), reused 0 (delta 0), pack-reused 563
Receiving objects: 100% (563/563), 338.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (359/359), done.
└──➤ openssl sha1 fauxjax/dist/fauxjax.min.js
SHA1(fauxjax/dist/fauxjax.min.js)= `ebb596de8ec286ac7f3be77ba6d4b3863a1233ff`

**Comment by JarrodCTaylor** [comment]
Let me know if this is resolved by d1d94c7

**Comment by JarrodCTaylor** [comment]
@khornberg is this resolved?

**Comment by khornberg** [comment]
Yep, thank you
