### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by jagthedrummer** [JarrodCTaylor/fauxjax#5]
I'm trying to use fauxjax along with Ember Data for testing. When I manage to wire up fauxjax to recognize a request properly I'm seeing an error thrown here : https://github.com/JarrodCTaylor/fauxjax/blob/master/src/fauxjax.js#L141

After the error is thrown my tests just hang and never progress any further.

I can work on putting together a tiny isolated example if it would help.

**Comment by JarrodCTaylor** [comment]
Fauxjax only works with jQuery 2.X an error on that particular line make me guess is you are using a 1.X version. If possible update your version of jQuery.

If you still have an issue put together an example and I will take a look.

**Comment by jagthedrummer** [comment]
Well, I'll be damned. I do indeed have jQuery 1.11.2. Kinda surprised that a brand new ember-cli app starts with 1.X instead of 2.X. Thanks for the info and quick response!

**Comment by JarrodCTaylor** [comment]
No worries. Holler if you run into any other snags.
