### ISSUE TITLE
Docs misleading on `type` vs `method`

### ISSUE THREAD

**Issue by dustinfarris** [JarrodCTaylor/fauxjax#7]
From [the docs](https://github.com/JarrodCTaylor/fauxjax/wiki/API-Reference#creating-fauxjax-handlers):

> type: A case-insensitive string specifying what HTTP method to match.

Should be:

> method: A case-insensitive string specifying what HTTP method to match.

**Comment by JarrodCTaylor** [comment]
Good call. Using type is just a legacy api. I will update it to be `method` instead.

**Comment by dustinfarris** [comment]
Ah, I was just reading the jQuery docs.  I guess `type` is valid—legacy, like you said.  From their docs:

> type (default: 'GET')
> Type: String
> An alias for method. You should use type if you're using versions of jQuery prior to 1.9.0.

It looks like whichever you use in the ajax call has to be the one you provide to fauxjax.

**Comment by JarrodCTaylor** [comment]
Closed with f51d6d787e2697c85abc9b8a4bd78a3dddd7551d
