### ISSUE TITLE
Query string support

### ISSUE THREAD

**Issue by TayHobbs** [JarrodCTaylor/fauxjax#9]
When I mock an endpoint(www.example.com/query-example/) and try to do a query(www.example.com/query-example/?query=im-a-query) I get 404's returned, even if I try to just mock the full url with the query at the end of it. 

In mockjax there is a 'response' hook that allows you to see the query when only mocking out the original url(www.example.com/query-example) and handle it in some way. Would it be possible to implement this in Fauxjax?

**Comment by JarrodCTaylor** [comment]
I just added a test attempting to recreate the 404 issue you are reporting. However, it appears to work as expected 

https://github.com/JarrodCTaylor/fauxjax/blob/master/test/queryParams.coffee

Let me know if you can write a failing test or if you have an example I can take a look at.

**Comment by JarrodCTaylor** [comment]
Based on our conversation it seems as though you are not dealing with a fauxjax issue but an Ember Data issue. Reopen if additional information is uncovered.

**Comment by TayHobbs** [comment]
Will do, thanks.
